version: '3.9'

services:
  db:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_DB: car-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"